### ISSUE TITLE
current tab page is truncated when tabline string is too long since open many tab pages.

### ISSUE THREAD

**Issue by extr15** [Sangdol/mintabline.vim#3]
Thanks for your plugin, and it's clear and useful.
When I open many tabpages for example 20 tabs, and each file name is pretty long, then the generated tabline string is too long, and excedding the current vim columns(window width), so only  the last 10 tabpage's titles are displayed, and the first 10 tabpage's titles are truncated. This is not convenient that I cannot see which tabpage is activated when I use the first 10 tabpages.
Could you fix this?

**Comment by Sangdol** [comment]
Thanks for opening the first issue.

I'm not sure what type of solution you're looking for, but I think [the tab max character length configuration](https://github.com/Sangdol/mintabline.vim?tab=readme-ov-file#gmintabline_tab_max_chars) could help:
```vim
let g:mintabline_tab_max_chars = 15
```
Have you tried this?

**Comment by extr15** [comment]
Thanks for your reply.
I know 'g:mintabline_tab_max_chars', but it won't help.
Maybe I didn't describe my problem clearly.
For example, I open 14 tabpages, and work on '11th' one (title highlighted):
![image](https://github.com/user-attachments/assets/8df37a7e-698c-4c7a-bf19-c65357d78b32)
When I jump to the '8th' tabpage, the tabline still display the last several tabpages since the vim width is limited (8th is high lighted but I can't see it):
![image](https://github.com/user-attachments/assets/3e6757f5-e478-487e-a0d7-9f4e86ea5f5b)
What I want is that the tabline likes:
...5 file 6 file 7 file **8 file** 9 file ...
i.e. the tabline can 'shift' to display currently activated tabpage.

p.s. GVim's 'guitablabel' don't have such problem, it will automatically shift to show the activated tabpage (there are "<" ">" in the two ends of the tab title):
![image](https://github.com/user-attachments/assets/d7a84be9-b9ca-47fd-a520-e9b1165cad1b)

**Comment by extr15** [comment]
Thanks for your quick fix.
I got your idea and have some thoughts.
It would be better if we can remember the last actived tab index. If we just jump between current activated tab and the last one, it will be better if the current displayed tab indexies **range** keep unchanged.
i.e. 
... 3 4 5 6 7 8 9 10 **`11`** 12 ...
... **`3`** 4 5 6 7 8 9 10 11 12 ...

instead of
...8 9 10 **`11`** 12 13 14...
1 2 **`3`** 4 5 6 7 8 9 ...

**Comment by extr15** [comment]
Instead of iterating to find the start and end displayed tab indexes (`while window_width < strchars(join(raw_tabs, ''))`), we can store length of each `raw_tab`, and make a `cumsum`, and use this `cumsum` and `window_width = &columns` and current and last activated tab index to find the start and end tab indexes.

**Comment by Sangdol** [comment]
@extr15 I've been thinking about it, but it doesn't seem to be a trivial problem. Addressing the issue will require a significant amount of code, which would exceed the current codebase. I'm not sure if the difference is worth it, so I'll merge the PR as it is for now. Let me know if you can think of a simple solution.

**Comment by extr15** [comment]
Thanks for your time. It indeed need some more time to implement the details.
